---
title: "preprocessing"
author: "Ehsan"
date: "10/27/2021"
output: html_document
---

# processing script
#
#this script loads the raw data, processes and cleans it 
#and saves it as Rds file in the processed_data folder

#load needed packages. make sure they are installed.
```{r}
library(readxl) #for loading Excel files
library(dplyr) #for data processing
library(here) #to set paths
library(tidyverse)
```

#path to data
#note the use of the here() package and not absolute paths
```{r}
data_location <- here::here("data","raw_data","Covid Vaccine data_Bangladesh_Abu_Sayeed.xlsx")
```
 

#but it adds typing. You can do it either way.
```{r}
rawdata <- readxl::read_excel(data_location)
```


```{r}
processeddata1 <- rawdata %>% rename ("education" = `Highest educational level`,
                               "student/heathworker" = `Are you a student or worker in the healthcare sector?`,
                               "economic_status" = 'Which of the following categories best describes your current socio-economic situation?',
                               "residence" = `Do you live in:`,
                               "trusted_source" = `Which source of COVID-19 information/advice do you trust the most?`,
                               "work_from_home" = 'Are you currently working/studying from home because of the COVID-19 outbreak?',
                               "quarantined_or_not" = `Have you been quarantined (either at home or else where) at any point in time during the Covid-19 epidemic?`,
                               "infection_status_info" = `Since the beginning of the COVID-19 outbreak, do you have information on your infection status?`,
                               "worry_level" = `How worried/fearful are you about becoming (re)infected by the coronavirus?: On a scale of 1 to 5`,)
```

```{r}
processeddata<- processeddata1 %>% mutate(across(where(is_character),as_factor))
```


```{r}
View(processeddata)
```

```{r}
str(processeddata)
```

# location to save file
```{r}
save_data_location <- here::here("data","processed_data","processeddata.rds")
```

```{r}
saveRDS(processeddata, file = save_data_location)
```

                         



